TEMPLATES = {
    "CONSORT": [
        "Title and abstract",
        "Introduction: Background and objectives",
        "Methods: Trial design",
        "Methods: Participants",
        "Methods: Interventions",
        "Methods: Outcomes",
        "Methods: Sample size",
        "Methods: Randomisation: Sequence generation",
        "Methods: Randomisation: Allocation concealment mechanism",
        "Methods: Randomisation: Implementation",
        "Methods: Blinding",
        "Methods: Statistical methods",
        "Results: Participant flow (diagram recommended)",
        "Results: Recruitment",
        "Results: Baseline data",
        "Results: Numbers analysed",
        "Results: Outcomes and estimation",
        "Results: Ancillary analyses",
        "Results: Harms",
        "Discussion: Limitations",
        "Discussion: Generalisability",
        "Discussion: Interpretation",
        "Other information: Registration",
        "Other information: Protocol",
        "Other information: Funding",
    ],
    "PRISMA": [
        "Title",
        "Abstract",
        "Introduction: Rationale",
        "Introduction: Objectives",
        "Methods: Protocol and registration",
        "Methods: Eligibility criteria",
        "Methods: Information sources",
        "Methods: Search",
        "Methods: Study selection",
        "Methods: Data collection process",
        "Methods: Data items",
        "Methods: Risk of bias in individual studies",
        "Methods: Summary measures",
        "Methods: Synthesis of results",
        "Methods: Risk of bias across studies",
        "Methods: Additional analyses",
        "Results: Study selection (flow diagram recommended)",
        "Results: Study characteristics",
        "Results: Risk of bias within studies",
        "Results: Results of individual studies",
        "Results: Synthesis of results",
        "Results: Risk of bias across studies",
        "Results: Additional analysis",
        "Discussion: Summary of evidence",
        "Discussion: Limitations",
        "Discussion: Conclusions",
        "Funding",
    ],
    "STARD": [
        "Title or abstract: Identification as a study of diagnostic accuracy",
        "Abstract: Structured summary",
        "Introduction: Scientific and clinical background",
        "Introduction: Study objectives and hypotheses",
        "Methods: Study design",
        "Methods: Participants: Eligibility criteria",
        "Methods: Participants: Sources and methods of participant selection",
        "Methods: Participants: Data collection",
        "Methods: Test methods: Index test details",
        "Methods: Test methods: Reference standard details",
        "Methods: Test methods: Rationale for choosing reference standard",
        "Methods: Test methods: Blinding",
        "Methods: Statistical methods: Handling of indeterminate results",
        "Methods: Statistical methods: Assessment of bias",
        "Methods: Statistical methods: Sample size calculation",
        "Methods: Statistical methods: Methods for estimating diagnostic accuracy",
        "Results: Participants: Flow diagram",
        "Results: Participants: Baseline demographic and clinical characteristics",
        "Results: Participants: Distribution of severity/alternative diagnoses",
        "Results: Test results: Cross tabulation of index test vs reference standard",
        "Results: Test results: Time interval and interventions between tests",
        "Results: Estimates: Diagnostic accuracy estimates with confidence intervals",
        "Results: Estimates: Adverse events from index test or reference standard",
        "Discussion: Study limitations",
        "Discussion: Implications for practice",
        "Other Information: Registration number and name of registry",
        "Other Information: Where the full study protocol can be accessed",
        "Other Information: Sources of funding and role of funders",
    ],
    "DEAL": [
         "Title and abstract",
         "Introduction: Rationale and objectives",
         "Methods: Steering group",
         "Methods: Facilitators",
         "Methods: Delphi panel selection and recruitment",
         "Methods: Initial item generation process",
         "Methods: Questionnaire design and pre-testing",
         "Methods: Number of Delphi rounds",
         "Methods: Definition of consensus and criteria",
         "Methods: Provision of feedback between rounds",
         "Methods: Stopping criteria for rounds",
         "Methods: Statistical analysis",
         "Results: Panel recruitment and retention",
         "Results: Round 1 participation and item ratings/responses",
         "Results: Round 2 participation and item ratings/responses (and subsequent rounds)",
         "Results: Final consensus items/statements",
         "Discussion: Summary of main findings",
         "Discussion: Strengths and limitations",
         "Discussion: Comparison with existing literature",
         "Discussion: Implications for practice or policy",
         "Other Information: Funding sources",
         "Other Information: Conflicts of interest",
    ]
}

def get_template_names():
    return list(TEMPLATES.keys())

def get_template_items(name):
    return TEMPLATES.get(name, []) 